export const users_request = 'http://localhost:5000/api/users/'
export const tenders_request = 'http://localhost:5000/api/tenders/'
export const tenders_request_home = 'http://localhost:5000/api/tenders'
export const bids_request = 'http://localhost:5000/api/bids/'
export const password_request = 'http://localhost:5000/api/password/'